development:
  adapter: postgresql
  encoding: unicode
  database: athletics_development
  pool: 5
  username: rob
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: athletics_test
  pool: 5
  username: rob
  password: password